# Generated by Django 5.0.4 on 2024-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_mobile_user_email_address_user_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
